### ISSUE TITLE
How do I add models?

### ISSUE THREAD

**Issue by Someone7un7** [blackestwhite/tele-sd#1]
for example what if I wanna download a model from civitai (or somewhere else) and use that model instead of the default model?

**Comment by blackestwhite** [comment]
based on this photo:
![image](https://github.com/blackestwhite/tele-sd/assets/33098161/b178dfc5-a3ec-4c66-aa9a-98828fe2cdfe)
the first parameter to the from_pretrained method is the path to the model, just download the model to your google drive then load it by passing the path as the first parameter to the corresponding method. (model should be compatible with the stable diffustion pipeline)
